Belt_Exam/Belt_Exam/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("apps.login.urls", namespace = "login")),
    url(r'^main/', include("apps.main.urls", namespace = "main")),
]

Belt_Exam/apps/login/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name = "index"),
    #need to register
    url(r'^login$', views.login, name = "login"),
    url(r'^register$', views.register, name = "register"),


        #need to success
    url(r'^success$', views.success, name = "success"),
        #need to logout
    url(r'^logout$', views.logout, name = "logout")
]

Belt_Exam/apps/login/models.py
from __future__ import unicode_literals
from django.db import models
import re, bcrypt
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

class UserManager(models.Manager):
    def register(self, postData):
        errors = [] #make a list of strings and append errors
        reply_to_veiws = {} # make an object to give a status and user_id back
        #put in valdatations can I validate for both login and register i dont think so so I'm going to make two methods but thats ok becuase my .Models pulls from the object?
        #check if firstname >2
        if len(postData["name"]) < 2:
            errors.append("First Name must be more than 2 character long")
        #check if user_name >2
        if len(postData["user_name"]) < 2:
            errors.append("First Name must be more than 2 character long")
        if not len(postData["date_hired"]):
            errors.append("Date can't be empty")
        #check if email matches regex and is not empty
        if not len(postData["email"].lower()):
            errors.append("Email is required")
        else:
            if not EMAIL_REGEX.match(postData["email"].lower()):
                errors.append("Enter a valid Email address")
        #check if email is unique
        if self.filter(email = postData["email"].lower()):
            errors.append("Email already in use")
        #check is password is null
        if len(postData["password"]) < 8:
            errors.append("Password must be more than 8 character long")
        if not postData["password"] == postData["password_confirm"]:
            errors.append("Passwords don't match")
        #Dump all the errors into errors{} so you can pass it back
        #return errors and a status of false

        #check is validations are true or false
        # if no errors then
        if not errors:
            #hash post data password
            hashed_password = bcrypt.hashpw(postData["password"].encode(), bcrypt.gensalt())
            #create the user self.create?
            user = self.create(name = postData["name"], user_name = postData["user_name"], email = postData["email"].lower(), date_hired= postData["date_hired"], password = hashed_password)
            #create a reply to the veiws with the user and a status true back to veiws
            reply_to_veiws["user"] = user
            reply_to_veiws["status"] = True

        # if errors
        else:
            #create a reply to the veiws with the user and a status true back to veiws
            reply_to_veiws["errors"] = errors
            reply_to_veiws["status"] = False

        return reply_to_veiws
    def login(self, postData):
        user =[]
        errors = [] #make a list of strings and append erros
        reply_to_veiws = {}
        # make an object to give a status and user_id back
        #put in valdatations can I validate for both login and register i dont think so so I'm going to make two methods but thats ok becuase my .Models pulls from the object?
        #first thing is to find an email from post data
        if postData:
            #FIXED##!!!! i think my email is case sensative look into fixing this if you have the time !!!!####
            user = self.filter(email = postData["email"].lower())
            if not EMAIL_REGEX.match(postData["email"].lower()):
                errors.append("Enter a valid Email address")

        if not user:

            errors.append("No email found please try again or register")
        #ok so here is where I want to do the password match to whats in the database
        #so its going to check the post data against the password thats stored for the email address and use bcrypts check hash, becuase i can return an empty user I should be ok to just check it against user.password
        #so first off find the password
        else:
            if not bcrypt.checkpw(postData["password"].encode(), user[0].password.encode()):

                errors.append("Password doesn't match login email")

        if not errors:

            reply_to_veiws["user"] = user.first()
            reply_to_veiws["status"] = True
        else:

            reply_to_veiws["errors"] = errors
            reply_to_veiws["status"] = False
        #Dump all the errors into errors{} so you can pass it back
        #return errors and a status of false
        return reply_to_veiws

# Create your models here.
class User(models.Model):
    name = models.CharField(max_length = 45)
    user_name = models.CharField(max_length = 45)
    email = models.CharField(max_length = 255)
    password = models.CharField(max_length = 255)
    date_hired = models.DateField(blank=True)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = UserManager()

Belt_Exam/apps/login/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib import messages
from .models import User
# Create your views here.
# should need

def index(request):



    return render(request, "login/index.html")

def login(request):
    reply_from_model = User.objects.login(request.POST)
    #if login status is true
    if reply_from_model["status"]:
        #return redirect("login:success")
        #save user id to session
        request.session["user_id"] = reply_from_model["user"].id
        return redirect("login:success")
    # if login status is false
    else:
        for error in reply_from_model["errors"]:
            messages.error(request, error)
        return redirect ("login:index")


def register(request):
    reply_from_model = User.objects.register(request.POST)
    #if login status is true
    if reply_from_model["status"]:
        #return redirect("login:success")
        #save user id to session
        request.session["user_id"] = reply_from_model["user"].id
        return redirect("login:success")
    # if login status is false
    else:
        for error in reply_from_model["errors"]:
            messages.error(request, error)
        return redirect ("login:index")

def success(request):

    # don't forget to filter to ensure that there is a user_id in sessions
    if not "user_id" in request.session:
        messages.error(request, "Must be logged in to continue")
        return redirect("login:index")
    return redirect("main:index")


def logout(request):
    request.session.clear()
    messages.error(request, "You are now logged out")
    return redirect("login:index")

Belt_Exam/apps/login/templates/login/index.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title></title>
</head>
<body>
  <h1>Login page</h1>
  <a href="{% url 'login:logout' %}">Logout</a>
  <div class="login">
    <h2>Login:</h2>
    <form class="" action="{% url 'login:login' %}" method="post">
      {% csrf_token %}
      <input type="text" name="email" value="name@username.com">
      <input type="password" name="password" value="password">
      <input type="submit" name="submit" value="submit">
    </form>
  </div>

  <div class="register">
    <h2>Register:</h2>
    <form class="" action="{% url 'login:register' %}"  method="post">
      {% csrf_token %}
      <ul>
        <li><label for="Name">Name:</label> <input type="text" name="name" value="name"></li>
        <li><label for="user_name">User Name:</label> <input type="text" name="user_name" value="user_name"></li>
        <li><label for="email">Email Address:</label><input type="email" name="email" value="name@username.com"></li>
        <li><label for="password">Password:</label><input type="password" name="password" value="password"></li>
        <li><label for="password_confirm">Confirm Password:</label> <input type="password" name="password_confirm" value="password"></li>
        <li><label for="date_hired">Hired Date:</label>  <input type="date" name="date_hired" value=""></li>
        <input type="submit" name="submit" value="submit">
      </ul>
    </form>
  </div>

  {% if messages %}
    {% for error in messages %}
      <p >{{error}}</p>
    {% endfor %}

  {% endif %}
  <!--include login and register all on this page  -->
  <!-- redirect to this page for errors from both login and register -->
</body>
</html>

Belt_Exam/apps/login/templates/login/login.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Login</title>
  {% load staticfiles %}
  <link rel="stylesheet" href="{% static 'login/css/style.css' %}"media="screen" title="no title"  charset="utf-8">
</head>
<body>
  <div class="loginwrapper">

    <form id="login" action="{% url 'login:login' %}" method="post">
       {% csrf_token %}
      <h1>Login</h1>
      <ul class="flex-outer">

           <li>
             <label for="email" >Email</label>
             <input type="email" id="email" name="email" placeholder="Enter your email here">
           </li>
           <li>
             <label for="password">Password</label>
             <input type="password" id="password" name="password" value="password" placeholder="Enter your password here">
           </li>
           <li>
             <button class="submit" type="submit">Submit</button>
               <a href="{% url 'login:index' %}" class="back">Back</a>
           </li>
         </ul>

    </form>
    {% if messages %}
    {% for error in messages %}
        <p >{{error}}</p>
    {% endfor %}
      <a href="{% url 'login:register' %}" class="back">Register</a>
    {% endif %}

  </div>
</body>
</html>

Belt_Exam/apps/login/templates/login/register.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Registration</title>
  {% load staticfiles %}
  <link rel="stylesheet" href="{% static 'login/css/style.css' %}"media="screen" title="no title"  charset="utf-8">
</head>
<body>
  <div class="loginwrapper">

    <form id="login" action="{% url 'login:submit_register' %}" method="POST">
       {% csrf_token %}
      <h1>Registration</h1>
      <ul class="flex-outer">
           <li>
             <label for="first_name">First Name:</label>
             <input type="text" id="first_name" name="first_name" min="2" placeholder="Enter your first name here">
           </li>
           <li>
             <label for="last_name">Last Name:</label>
             <input type="text" id="last_name" name="last_name"  min="2" placeholder="Enter your last name here">
           </li>
           <li>
             <label for="email">Email:</label>
             <input type="email" id="email" name = "email" placeholder="Enter your email here">
           </li>
           <li>
             <label for="password">Password:</label>
             <input type="password" id="password" name ="password" value ="password" min=6 placeholder= " Enter your password here" >
           </li>
           <li>
             <label for="message"> Confirm :</label>
             <input  type="password" id="password_confirm" name="password_confirm" value ="password" min=6 placeholder="Confirm your password here"></textarea>
           </li>

           <li>
             <button class="submit" type="submit">Submit</button>
            <!-- <button class ="back" type="submit" value="Back">Back</button> -->
            <a href="{% url 'login:index' %}" class="back">Back</a>
           </li>
         </ul>

    </form>
    {% if messages %}
    {% for error in messages %}
        <p >{{error}}</p>
    {% endfor %}
      <a href="{% url 'login:register' %}" class="back">Register</a>
    {% endif %}
  </div>
</body>
</html>

Belt_Exam/apps/login/templates/login/success.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Success</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'login/css/style.css' %}"media="screen" title="no title"  charset="utf-8">
  </head>
  <body>
    <h1>You are now logged in</h1>
    <p>Welcome {{request.session.first_name}} your user ID is {{request.session.user_id}}</p>
    <a href="{% url 'wish_list:index' %}">Go to wish_list</a>
  </body>
</html>