Belt_Exam/Belt_Exam/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("apps.login.urls", namespace = "login")),
    url(r'^main/', include("apps.main.urls", namespace = "main")),
]

Belt_Exam/apps/login/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name = "index"),
    #need to register
    url(r'^login$', views.login, name = "login"),
    url(r'^register$', views.register, name = "register"),


        #need to success
    url(r'^success$', views.success, name = "success"),
        #need to logout
    url(r'^logout$', views.logout, name = "logout")
]

Belt_Exam/apps/main/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [

    url(r'^$', views.index, name = "index"),
    url(r'^add_appointment$', views.add_appointment, name = "add_appointment"),
    url(r'^edit_appointment/(?P<appointment_id>\d+)$', views.edit_appointment, name = "edit_appointment"),
    url(r'^confirm_edit_appointment/(?P<appointment_id>\d+)$', views.confirm_edit_appointment, name = "confirm_edit_appointment"),
    url(r'^delete_appointment/(?P<appointment_id>\d+)$', views.delete_appointment, name = "delete_appointment"),



]

Belt_Exam/apps/main/models.py
from __future__ import unicode_literals
from django.db import models
from datetime import date, time, datetime
from dateutil.parser import parse as parse_date
from .. login.models import User


# Create your models here.
def validate_empty_fields(postData, errors):
    if not len(postData["task"]):
        errors.append("Please enter a task")
    if not len(postData["date"]):
        errors.append("Due Date can't be empty")
    if not len(postData["time"]):
        errors.append("Time can't be empty")

def validate_duplicate_appointments(user_id, postData, errors):
    user = User.objects.get(id = user_id)
    current_appointments = Appointment.objects.filter(created_by = user)
    for appointment in current_appointments:
        if (parse_date(postData["date"]).date() == appointment.start_date
            and parse_date(postData["time"]).time() == appointment.start_time):
            errors.append("Time slot already filled")

def validate_future_appointments(user_id, postData, errors):
    if parse_date(postData["date"]).date() == datetime.today().date():
        if parse_date(postData["time"]).time() < datetime.today().time():
            errors.append("Appointment time must be in the future")

    #else if the date is not today that it's in the future
    elif parse_date(postData["date"]).date() < datetime.today().date():
        errors.append("Appointment date must be in the future")

class AppointmentManager(models.Manager):


    def create_appointment(self, postData, user_id):
        #make an appointment with validations
        reply_to_veiws = {}
        errors = []
        validate_empty_fields(postData, errors)
        if not errors:
            #check if the entered data and time match any other dates and times for this user
            validate_duplicate_appointments(user_id, postData, errors)
            validate_future_appointments(user_id, postData, errors)

        #might need a few more validations for time but lets run with this for now
        if not errors:
            user = User.objects.get(id = user_id)
            date_from_form = parse_date(postData["date"]).date()
            print (date_from_form)
            time_from_form = parse_date(postData["time"]).time()
            appointment = self.create(task = postData["task"], created_by = user, start_date =  parse_date(postData["date"]), start_time =  parse_date(postData["time"]), status = "Pending")
            reply_to_veiws["appointment"] = appointment
            reply_to_veiws["status"] = True

        else:
            reply_to_veiws["errors"] = errors
            reply_to_veiws["status"] = False
        return reply_to_veiws

    def edit_appointment(self, postData, appointment_id, user_id):
        #make an appointment with validations
        reply_to_veiws = {}
        errors = []
        #same validations as create_appointment
        validate_empty_fields(postData, errors)
        if not errors:
            validate_duplicate_appointments(user_id, postData, errors)
            validate_future_appointments(user_id, postData, errors)

        if not errors:

            appointment = Appointment.objects.get(id = appointment_id)

            appointment.task = postData["task"]
            appointment.start_date =  parse_date(postData["date"])
            appointment.start_time =  parse_date(postData["time"])
            appointment.status = postData["status"]
            appointment.save()

            reply_to_veiws["appointment"] = appointment
            reply_to_veiws["status"] = True

        else:
            reply_to_veiws["errors"] = errors
            reply_to_veiws["status"] = False
        return reply_to_veiws

    def update_status(self):
        #every time you log into your main page update all of the statuses the possible options are defualt = Pending, user updated = Done, in the past and not done = Missed

        all_appointments = Appointment.objects.all()
        for appointment in all_appointments:
            if (appointment.status != "Done"
                and appointment.start_date <= date.today()
                and appointment.start_time < datetime.today().time()):
                appointment.status = "Missed"
                appointment.save()

    def delete_appointment(self, appointment_id):
        #make an appointment with validations

        appointment = Appointment.objects.get(id = appointment_id)
        appointment.delete()
        return

class Appointment(models.Model):
    task = models.CharField(max_length = 255)
    created_by = models.ForeignKey(User, related_name = 'user_created_by')
    status = models.CharField(max_length = 255)
    #not sure if I need a time and date field or do both in one?
    start_date = models.DateField(blank=True)
    start_time = models.TimeField(blank=True)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = AppointmentManager()

Belt_Exam/apps/main/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib import messages
from datetime import date, datetime
from dateutil.parser import parse as parse_date
from .. login.models import User
from .models import Appointment
# Create your views here.

def index(request):
    if not "user_id" in request.session:
        messages.error(request, "Must be logged in to continue")
        return redirect("login:index")
    now = datetime.today()
    Appointment.objects.update_status()
    #pass over my user to make it accessable in my template
    current_user = User.objects.get(id = request.session["user_id"])
    #some logic to filter by date likely start with all appointments and then filter stuff out before shoving it into a context variable
    todays_appointments = Appointment.objects.filter(start_date = now, created_by = current_user ).order_by('start_time')
    #some logic to filter by date
    other_appointments = Appointment.objects.filter(created_by = current_user).exclude(start_date = now, ).order_by('start_date', 'start_time')

    context = {
        "current_user" : current_user,
        "todays_appointments" : todays_appointments,
        "other_appointments" : other_appointments,
        "now" : now
    }
    return render(request, "main/index.html", context)

def add_appointment(request):
    if not "user_id" in request.session:
        return redirect ("login:index")
    if not request.method == "POST":
        return redirect ("main:index")

    responce_from_model = Appointment.objects.create_appointment(request.POST, request.session["user_id"])

    if responce_from_model["status"]:
        messages.error(request, "You added an Appointment")
        return redirect("main:index")
    else:
        for error in responce_from_model["errors"]:
            messages.error(request, error)
        return redirect("main:index")

def edit_appointment(request, appointment_id):
    if not "user_id" in request.session:
        return redirect ("login:index")
    if not request.method == "POST":
        return redirect ("main:index")
    appointment = Appointment.objects.get(id = appointment_id)
    context = {
        "appointment" : appointment
    }

    return render(request, "main/edit_appointment.html", context)

def confirm_edit_appointment(request, appointment_id):
    if not "user_id" in request.session:
        return redirect ("login:index")
    if not request.method == "POST":
        return redirect ("main:index")
    appointment = Appointment.objects.get(id = appointment_id)
    responce_from_model = Appointment.objects.edit_appointment(request.POST, appointment_id, request.session["user_id"])
    context = {
        "appointment" : appointment
    }
    if responce_from_model["status"]:
        messages.error(request, "You updated an Appointment")
        return redirect("main:index")
    else:
        for error in responce_from_model["errors"]:
            messages.error(request, error)
        return render(request, "main/edit_appointment.html", context)



def delete_appointment(request, appointment_id):
    if not request.method == "POST":
        return redirect ("main:index")

    Appointment.objects.delete_appointment(appointment_id)
    return redirect("main:index")

Belt_Exam/apps/main/templates/main/edit_appointment.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <a href="{% url 'login:logout' %}">logout</a>
    <a href="{% url 'main:index' %}">Dashboard</a>

    <form class="" action="{% url 'main:confirm_edit_appointment' appointment.id %}" method="post">
      {% csrf_token %}
      <ul>
        <li><label for="Task">Task:</label> <input type="text" name="task" value="{{appointment.task}}"></li>
        <li><label for="status">status:</label>
        <select name = "status">
          <option value="Pending">Pending</option>
          <option value="Done">Done</option>
          <option value="Missed">Missed</option>
        </select></li>
        <li><label for="date">Date:</label><input type="date" name="date" value= '{{appointment.start_date |date:"Y-m-d"}}'></li>
        <li><code>{{appointment.start_date }}</code></li>
        <li><code>{{appointment.start_date |date:"Y-m-d"}}</code></li>
        <li><label for="time">Time:</label> <input type="time" name="time" value= '{{appointment.start_time |date:"H:i"}}'></li>
        <input type="submit" name="Update" value="Update">
      </ul>
    </form>

    {% if messages %}
      {% for error in messages %}
      <p >{{error}}</p>
      {% endfor %}
    {% endif %}
  </body>
</html>

Belt_Exam/apps/main/templates/main/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <a href="{% url 'login:logout' %}">logout</a>
  <h1>Hello {{current_user.name}}</h1>
  <p>Here are your appointments for today, {{now}}</p>
  <table>
    <tr>
      <th>Tasks</th>
      <th>Time</th>
      <th>Status</th>
      <th>Action</th>
    </tr>
    {% for appointment in todays_appointments %}
    <tr>
      <td>{{appointment.task}}</td>
      <td>{{appointment.start_time}}</td>
      <td>{{appointment.status}}</td>
      <td>{% if appointment.status == "Pending" %}<form class="" action="{% url 'main:edit_appointment' appointment.id %}" method="post">
         {% csrf_token %}
        <input type="submit" name="edit" value="edit">
      </form> <form class="" action="{% url 'main:delete_appointment' appointment.id %}" method="post">
         {% csrf_token %}
        <input type="submit" name="delete" value="delete">
      </form>{% endif %}</td>
    </tr>
    {% endfor %}
  </table>

  <p>Here are your other appointments </p>
  <table>
    <tr>
      <th>Tasks</th>
      <th>Time</th>
      <th>Action</th>
    </tr>
    {% for appointment in other_appointments %}
    <tr>
      <td>{{appointment.task}}</td>
      <td>{{appointment.start_date}}</td>
      <td>{{appointment.start_time}}</td>
      <td><form class="" action="{% url 'main:edit_appointment' appointment.id %}" method="post">
         {% csrf_token %}
        <input type="submit" name="edit" value="edit">
      </form> <form class="" action="{% url 'main:delete_appointment' appointment.id %}" method="post">
         {% csrf_token %}
        <input type="submit" name="delete" value="delete">
      </form></td>
    </tr>
    {% endfor %}
  </table>

  <h2>Add Appointment</h2>
  <form class="" action="{% url 'main:add_appointment' %}" method="post">
    {% csrf_token %}
    <input type="date" name="date" value="">
    <input type="time" name="time" value="">
    <input type="text" name="task" value="">
    <input type="submit" name="submit" value="submit">

  </form>

  {% if messages %}
    {% for error in messages %}
    <p >{{error}}</p>
    {% endfor %}
  {% endif %}
  </body>
</html>

Belt_Exam/apps/main/templates/main/next_page.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>You made it to the next route</h1>
    <a href="{% url 'login:logout' %}">Logout</a>
    <a href="{% url 'main:next_page' %}">next_page</a>
    <a href="{% url 'main:index' %}">home</a>
  </body>
</html>